import type { Metadata } from "next";
import { Onest } from "next/font/google";
import "./globals.css";
import {AuthProvider} from "./Providers"


const onest = Onest({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Teachers Dashboard",
  description: "Generated by create next app",
  icons:{
    icon:['/favicon.ico?v=4'],
    apple:['/apple-touch-icon.png?v=4'],
    shortcut:['/apple-touch-icon.png']
  }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={onest.className}>
        <AuthProvider>
        {children}
        </AuthProvider>
        </body>
    </html>
  );
}
